# Generated by Django 4.0.3 on 2022-03-11 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_seller_alter_customer_options_alter_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
