# Generated by Django 4.0.3 on 2022-03-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_address_alter_customer_address'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
