# Generated by Django 4.0.3 on 2022-03-26 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_address_created_at_address_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.IntegerField(choices=[(0, 'Guest'), (1, 'Customer')], default=0),
        ),
    ]
